language: node_js
cache:
  yarn: true
  directories:
    - ~/.npm
notifications:
  email: false
install:
    - yarn --ignore-engines
node_js:
  - '10'
  - '11'
  - '12'
script:
  - yarn jest

after_success:
  - yarn run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
